### ISSUE TITLE
Can this be used in Emails?

### ISSUE THREAD

**Issue by itzmesaran** [commonpike/add-to-calendar-buttons#20]
Hello, Came across this useful module. Thanks for all your work on this. I understand this can be easily integrated into Websites/landing pages.
But is it possible to use this solution in emails? Email clients don't like script tags, so what you'd advise?

**Comment by commonpike** [comment]
Hello Itzmesaran, 

Emails don't support javascript, thank god. But in the end, the 'add to calendar' links are not javascripty at all, they are just links. If you look at the 3rd example here

https://commonpike.github.io/add-to-calendar-buttons/example.html

The script generated 5 different links that you can just copy/paste into either a webpage or an email. Ofcourse, each different platform (outlook,apple,etc) has its own link.
