### ISSUE TITLE
Hiding/Disable "See Guest List"

### ISSUE THREAD

**Issue by rhythm49** [commonpike/add-to-calendar-buttons#6]
Hello,

Thanks for sharing this library, it's really great!

Is it possible to hide/disable the "See Guest List" that shows up in the Google Calendar? I can't seem to figure it out.

Any ideas?

Thanks!

**Comment by commonpike** [comment]
No :-/ 

The best introduction I found is https://github.com/InteractionDesignFoundation/add-event-to-calendar-docs/blob/master/services/google.md

.. and it doesn't mention the 'show guest list'
