### ISSUE TITLE
add to calendar data -- issue

### ISSUE THREAD

**Issue by Fahad-pnw** [commonpike/add-to-calendar-buttons#9]
addToCalendar function works just fine..however it does create an entire html element.
addToCalendar should do just about that, however doing that results in empty variables for time+every other calendar field. It does generate all the info, the info isn't present in the fields.
https://prnt.sc/pewlbd

**Comment by Fahad-pnw** [comment]
seems like the issue was in minified version, loaded the full version and its good to go! thanks for maintaining!

**Comment by commonpike** [comment]
I was thinking that when I saw this, but I didn't understand what you were saying.

Now I do, and the problem was add-to-calendar.min.js was not updated after a final bug fix. Did that now, so the minified version should work now too (in the master branch).

I think you **meant** to say

> addToCalendar**Data**() function works just fine..however [...] It does generate all the **fields**, the info isn't present in the fields.

**Comment by Fahad-pnw** [comment]
> addToCalendar function works just fine..however it does create an entire html element.
> **addToCalendarData** should do just about that, however doing that results in empty variables for time+every other calendar field. It does generate all the info, the info isn't present in the fields.
> https://prnt.sc/pewlbd


yes, sorry, typo!
